# Generated by Django 5.0.2 on 2025-03-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseresume',
            old_name='skill',
            new_name='keyword',
        ),
    ]
