# Generated by Django 5.0.2 on 2025-03-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Data Source',
                'db_table': 'data_source',
            },
        ),
    ]
