# Generated by Django 5.0.2 on 2025-03-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Supervisor Status',
                'db_table': 'supervisor_status',
            },
        ),
    ]
