# Generated by Django 5.0.2 on 2025-01-22 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('actor_id', models.CharField(max_length=100)),
                ('actor_name', models.CharField(max_length=500)),
                ('days', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobBoardResult',
            fields=[
                ('job_title', models.CharField(max_length=220)),
                ('job_description', models.TextField()),
                ('source', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=220)),
                ('priority', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_scraped', models.DateTimeField()),
                ('run_id', models.CharField(max_length=50)),
                ('date_job_posted', models.DateField()),
                ('salary', models.CharField(max_length=100)),
                ('job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('job_url', models.URLField(max_length=500)),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('job_description_is_mismatch', models.BooleanField(default=False)),
                ('who_flagged_job_description_is_mismatch', models.CharField(blank=True, max_length=50, null=True)),
                ('is_complex_form', models.BooleanField(default=False)),
                ('apply_type', models.CharField(blank=True, max_length=50, null=True)),
                ('external_apply_url', models.URLField(blank=True, max_length=500, null=True)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_job_results', to='scraper.configuration')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run_id', models.CharField(max_length=50, unique=True)),
                ('dataset_id', models.CharField(blank=True, max_length=50, null=True)),
                ('job_board', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('input_json', models.JSONField(blank=True, null=True)),
                ('output_json', models.JSONField(blank=True, null=True)),
                ('run_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_history', to='scraper.configuration')),
            ],
            options={
                'verbose_name_plural': 'Scrape Histories',
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='scraper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_configurations', to='scraper.scraper'),
        ),
    ]
