# Generated by Django 5.1.5 on 2025-02-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApifyKey',
            new_name='ApiToken',
        ),
        migrations.AlterModelOptions(
            name='apitoken',
            options={'verbose_name_plural': 'ApiTokens'},
        ),
        migrations.AlterModelTable(
            name='apitoken',
            table='ApiToken',
        ),
    ]
