# Generated by Django 5.0.2 on 2025-01-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_scraper_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobboardresult',
            old_name='job_description_is_mismatch',
            new_name='job_mismatch',
        ),
        migrations.RemoveField(
            model_name='jobboardresult',
            name='apply_type',
        ),
        migrations.RemoveField(
            model_name='jobboardresult',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='jobboardresult',
            name='who_flagged_job_description_is_mismatch',
        ),
        migrations.RemoveField(
            model_name='scrapehistory',
            name='output_json',
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='applied_for_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='apply_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='customized_resume_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='date_applied_for',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='date_apply_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='date_job_removed_from_site',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='date_resume_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='failure_applying',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='general_notes',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='is_easyapply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='is_request_regeneration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='lock_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='problem_applying_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobboardresult',
            name='who_jd_mismatch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scrapehistory',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jobboardresult',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobboardresult',
            name='date_job_posted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jobboardresult',
            name='date_scraped',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jobboardresult',
            name='external_apply_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobboardresult',
            name='job_title',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='jobboardresult',
            name='job_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobboardresult',
            name='job_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobboardresult',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobboardresult',
            name='run_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobboardresult',
            name='salary',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobboardresult',
            name='skill',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='jobboardresult',
            name='source',
            field=models.CharField(default='', max_length=50),
        ),
    ]
