# Generated by Django 5.0.2 on 2025-03-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_jobboardresult_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobboardresult',
            name='salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
