# Generated by Django 5.0.2 on 2025-01-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_rename_job_description_is_mismatch_jobboardresult_job_mismatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='days',
        ),
        migrations.AddField(
            model_name='configuration',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
