# Generated by Django 5.0.2 on 2025-03-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_jobboardresult_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
