# Generated by Django 5.0.2 on 2025-01-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_remove_scraper_days_configuration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='job_board',
            field=models.CharField(default='', max_length=50),
        ),
    ]
