# Generated by Django 5.0.2 on 2025-01-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_configuration_job_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='job_board',
        ),
    ]
