# Generated by Django 5.0.2 on 2025-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_remove_configuration_job_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapehistory',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
