# Generated by Django 5.0.2 on 2025-03-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_alter_configuration_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
