# Generated by Django 5.0.2 on 2025-01-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_scrapehistory_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapehistory',
            name='number_of_jobs',
            field=models.IntegerField(default=0),
        ),
    ]
