# Generated by Django 5.0.2 on 2025-01-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_scrapehistory_number_of_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobboardresult',
            name='salary',
            field=models.CharField(default=50),
        ),
    ]
