# Generated by Django 5.0.2 on 2025-03-20 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_alter_configuration_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobboardresult',
            name='qualification',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='JobBoardResume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(default='', max_length=220)),
                ('job_description', models.TextField()),
                ('source', models.CharField(default='', max_length=50)),
                ('skill', models.CharField(default='', max_length=220)),
                ('date_resume_created', models.DateTimeField(null=True)),
                ('date_scraped', models.DateTimeField(null=True)),
                ('run_id', models.CharField(default='', max_length=50)),
                ('date_job_posted', models.DateTimeField(null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('job_type', models.CharField(default='', max_length=50)),
                ('company', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('job_url', models.URLField(max_length=500, null=True)),
                ('customized_resume_url', models.URLField(max_length=500, null=True)),
                ('applied_for_by', models.CharField(default='', max_length=100)),
                ('date_applied_for', models.DateTimeField(null=True)),
                ('general_notes', models.CharField(default='', max_length=500)),
                ('is_request_regeneration', models.BooleanField(default=False)),
                ('job_mismatch', models.BooleanField(default=False)),
                ('who_jd_mismatch', models.CharField(default='', max_length=100)),
                ('is_complex_form', models.BooleanField(default=False)),
                ('is_easyapply', models.BooleanField(default=False)),
                ('apply_status', models.CharField(default='', max_length=100)),
                ('failure_applying', models.IntegerField(default=0)),
                ('external_apply_url', models.URLField(max_length=500, null=True)),
                ('lock_application', models.BooleanField(default=False)),
                ('date_apply_started', models.DateTimeField(null=True)),
                ('date_job_removed_from_site', models.DateTimeField(null=True)),
                ('problem_applying_description', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_job_resumes', to='scraper.configuration')),
            ],
            options={
                'db_table': 'jobboard_resumes',
            },
        ),
    ]
