# Generated by Django 5.0.2 on 2025-03-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_jobboardresult_qualification_jobboardresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobboardresult',
            name='qualification',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
