# Generated by Django 5.0.2 on 2025-01-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_alter_jobboardresult_salary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuration',
            table='configurations',
        ),
        migrations.AlterModelTable(
            name='jobboardresult',
            table='jobboard_results',
        ),
        migrations.AlterModelTable(
            name='scrapehistory',
            table='scrape_histories',
        ),
        migrations.AlterModelTable(
            name='scraper',
            table='scrapers',
        ),
    ]
