# Generated by Django 5.0.2 on 2025-03-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_alter_jobboardresult_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobboardresult',
            old_name='qualification',
            new_name='is_qualified',
        ),
    ]
