# Generated by Django 5.0.2 on 2025-01-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_alter_configuration_table_alter_jobboardresult_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApifyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Apify API Key',
                'db_table': 'apify_key',
            },
        ),
    ]
