# Generated by Django 5.0.2 on 2025-01-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_apifykey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapehistory',
            options={'verbose_name_plural': 'Scrape History'},
        ),
        migrations.AlterModelTable(
            name='scrapehistory',
            table='scrape_history',
        ),
    ]
