# Generated by Django 5.0.2 on 2025-03-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_rename_qualification_jobboardresult_is_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobboardresume',
            name='ai_response_job_analyzer',
            field=models.TextField(null=True),
        ),
    ]
