# Generated by Django 5.0.2 on 2025-03-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_jobboardresume_ai_response_job_analyzer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobboardresult',
            name='job_type',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
