# Generated by Django 5.0.2 on 2025-03-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_alter_jobboardresult_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobboardresume',
            name='job_type',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
