# Generated by Django 5.0.2 on 2025-01-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_userinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='index',
            field=models.IntegerField(default=-1),
        ),
    ]
